### ISSUE TITLE
did not start with actual node lts

### ISSUE THREAD

**Issue by Sungamm** [Martvvliet/homebridge-mi-flora-filtered#14]
Hi Guys, 

I updated my homebridge today incl. the node version. 

node.js 14.15.0
npm 6.14.8

after a reboot the homebridge-mi-flora-filtered plug-in did not start proper and the complete homebridge shutdown.

`Nov 10 21:36:37 raspberrypi homebridge[9515]: [10/11/2020, 21:36:37] ERROR LOADING PLUGIN homebridge-mi-flora-filtered:
Nov 10 21:36:38 raspberrypi homebridge[9515]: [10/11/2020, 21:36:38] Error: The module '/usr/local/lib/node_modules/homebridge-mi-flora-filtered/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'
Nov 10 21:36:38 raspberrypi homebridge[9515]: was compiled against a different Node.js version using
Nov 10 21:36:38 raspberrypi homebridge[9515]: NODE_MODULE_VERSION 72. This version of Node.js requires
Nov 10 21:36:38 raspberrypi homebridge[9515]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
Nov 10 21:36:38 raspberrypi homebridge[9515]: the module (for instance, using `npm rebuild` or `npm install`).
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at require (internal/modules/cjs/helpers.js:88:18)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-flora-filtered/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Nov 10 21:36:38 raspberrypi homebridge[9515]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
`

I tried out again
`sudo npm install --unsafe-perm -g bluetooth-hci-socket
sudo npm install -g --unsafe-perm @abandonware/noble
sudo npm install -g --unsafe-perm node-gyp`
but this didnt help.

Have anybode a tipp, please?

Currently I remove the entry in the config.json and the homebridge restart again, but without the xiaomi sensons of course. 

Thank you!

**Comment by Sungamm** [comment]
I solved the problem for me today. 

I removed the xiaomi from config. removed the plug-in. 

used apt-get update & upgrade. re-installed the xiaomi plugin again and enter the config. 

Restart and it works!
