### ISSUE TITLE
No Data is updated

### ISSUE THREAD

**Issue by Bladestar2105** [Martvvliet/homebridge-mi-flora-filtered#3]
Hello,

today I installed your Plugin on my HOOBS Homebridge without any errors.
After configuration the Flower-Sensor was visible in the Home-App but no data was updated after several hours. I think the issue can be, that "sudo hcitool lescan" threw an error and I had to use "sudo bluetoothctl scan on" scanning for devices. The MAC-Address I used in the configuration of HOOBS.
Thank you for your help! :-)

**Comment by Martvvliet** [comment]
@Bladestar2105 Do you use a rpi3?

**Comment by Bladestar2105** [comment]
No, I use a Debian Virtual machine with Bluetooth Controller passthrough.

**Comment by Martvvliet** [comment]
Hmm, currently it is only tested on the rpi 3. This is probably the reason why it isn't working on your system.

**Comment by Donni1966** [comment]
Hi, 
i get  also several error install this
sudo npm install --unsafe-perm -g bluetooth-hci-socket
sudo npm install -g --unsafe-perm @abandonware/noble
sudo npm install -g --unsafe-perm node-gyp

Some Errors build 
make: *** [binding.target.mk:109: Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/bluetooth-hci-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bluetooth-hci-socket@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-23T18_58_20_161Z-debug.log

and i install the plugin, but no data comes in. 

i am running on a rp4  that the reason?

**Comment by LostJen** [comment]
It will succeed to install on a pi 4 if you try to install the plug in.  It pulls cached references to finish.

**Comment by Donni1966** [comment]
try to understand this. 

Ih installed this part
sudo npm install --unsafe-perm -g bluetooth-hci-socket
sudo npm install -g --unsafe-perm @abandonware/noble
sudo npm install -g --unsafe-perm node-gyp

than i install the plugin.

No change until now. No Data 

Is there a log file anywhere?
